version: 0.1

phases:
  install:
    commands:
      - echo "nothing to do in install"
  pre_build:
    commands:
      - echo "Installing dependencies - `pwd`"
      - cd app && npm install
      - echo "dependencies install completed `date`"
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
  discard-paths: yes
